spring:
  version: @project.version@
  application:
    name: @project.artifactId@
    des: "Controller of ZPUTech Cloud Real Machine Platform"
  profiles:
    active: @project.artifactId@,eureka,jdbc,feign,logging,user
  main:
    allow-circular-references: true
